# Generated by Django 4.0.1 on 2022-01-14 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_comment_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=225)),
                ('checkout_id', models.CharField(max_length=225)),
                ('created', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(auto_now=True)),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentintent')),
            ],
        ),
    ]
